### ISSUE TITLE
Icons shift when zooming

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/aar.gruppe-adler.de#5]
![](https://i.imgur.com/E4P7Bjn.gif)

**Comment by Dahlgren** [comment]
https://gis.stackexchange.com/questions/222971/how-can-i-prevent-leaflet-from-moving-my-marker-while-zooming-into-the-map

**Comment by DerZade** [comment]
Thanks a lot, but I'm pretty sure its not about the icon anchor, because I'm actually generating the icon myself ([see here](https://github.com/gruppe-adler/aar.gruppe-adler.de/blob/master/src/models/UnitMarker.ts#L37)). So if there is an error it is most likely in there.

The weirdest thing is that the icon of Willard (inside the airbase) doesn't shift like all others do. 🤔 
See for yourself: https://aar.gruppe-adler.de/replay/6

**Comment by Dahlgren** [comment]
Ah, different issue from ours then. Our markers jump during the zoom animation 🔍
